// CSV 가져오기 템플릿 정의 — 라이선스, 조직원, 그룹, 할당, 시트, 클라우드, 도메인, 하드웨어

import type { ImportType } from "@/lib/csv-import";

type TemplateDefinition = {
  label: string;
  headers: string[];
  sampleRows: string[][];
};

export const templates: Record<ImportType, TemplateDefinition> = {
  licenses: {
    label: "라이선스",
    headers: [
      "name",
      "totalQuantity",
      "purchaseDate",
      "key",
      "licenseType",
      "price",
      "expiryDate",
      "noticePeriodDays",
      "adminName",
      "description",
      "parentLicenseName",
      "vendor",
      "paymentCycle",
      "unitPrice",
      "currency",
      "exchangeRate",
    ],
    sampleRows: [
      [
        "Open VPN",
        "10",
        "2024-01-15",
        "XXXXX-XXXXX-XXXXX",
        "VOLUME",
        "150000",
        "2025-01-15",
        "30",
        "김관리",
        "VPN 상위 라이선스",
        "",
        "OpenVPN Inc.",
        "YEARLY",
        "15000",
        "KRW",
        "1",
      ],
      [
        "GitHub Teams",
        "30",
        "2024-06-01",
        "",
        "NO_KEY",
        "500000",
        "2025-06-01",
        "90",
        "이담당",
        "계정 기반 서비스",
        "",
        "GitHub",
        "MONTHLY",
        "4",
        "USD",
        "1350",
      ],
    ],
  },
  employees: {
    label: "조직원",
    headers: ["name", "department", "email", "title", "companyName", "orgUnitName", "groupName"],
    sampleRows: [
      ["홍길동", "개발팀", "hong@example.com", "선임연구원", "본사", "백엔드팀", "기본 그룹"],
      ["김철수", "마케팅팀", "kim@example.com", "", "", "", ""],
    ],
  },
  groups: {
    label: "그룹",
    headers: ["name", "description", "isDefault", "licenseNames"],
    sampleRows: [
      ["기본 그룹", "신규 입사자 기본 할당", "true", "Microsoft 365 Business;Slack"],
      ["디자인팀 그룹", "디자인팀 전용 라이선스", "false", "Adobe Creative Cloud"],
    ],
  },
  assignments: {
    label: "할당",
    headers: ["licenseName", "employeeEmail", "assignedDate", "reason"],
    sampleRows: [
      ["Microsoft 365 Business", "hong@example.com", "2024-06-01", "입사 시 할당"],
      ["Slack", "kim@example.com", "", ""],
    ],
  },
  seats: {
    label: "시트(키)",
    headers: ["licenseName", "key"],
    sampleRows: [
      ["Adobe Acrobat Pro", "ABCDE-12345-FGHIJ"],
      ["Adobe Acrobat Pro", "KLMNO-67890-PQRST"],
    ],
  },
  cloud: {
    label: "클라우드 자산",
    headers: [
      "name",
      "vendor",
      "platform",
      "accountId",
      "region",
      "serviceCategory",
      "resourceType",
      "resourceId",
      "instanceSpec",
      "monthlyCost",
      "currency",
      "billingCycle",
      "purchaseDate",
      "expiryDate",
      "description",
      "assigneeName",
      "companyName",
      "orgUnitName",
    ],
    sampleRows: [
      [
        "운영서버 EC2",
        "AWS",
        "AWS",
        "123456789012",
        "ap-northeast-2",
        "IaaS",
        "EC2",
        "i-0abc123def456",
        "t4g.small",
        "50000",
        "KRW",
        "MONTHLY",
        "2024-01-01",
        "",
        "운영 웹서버",
        "",
        "본사",
        "인프라팀",
      ],
      [
        "Slack Business+",
        "Slack",
        "Slack",
        "team@company.com",
        "",
        "SaaS",
        "Web/App",
        "",
        "",
        "8500",
        "USD",
        "MONTHLY",
        "2024-06-01",
        "2025-06-01",
        "사내 메신저",
        "",
        "",
        "",
      ],
    ],
  },
  domains: {
    label: "도메인·SSL",
    headers: [
      "name",
      "domainName",
      "registrar",
      "sslType",
      "issuer",
      "cost",
      "currency",
      "purchaseDate",
      "expiryDate",
      "autoRenew",
      "description",
      "companyName",
      "orgUnitName",
    ],
    sampleRows: [
      [
        "example.com",
        "example.com",
        "가비아",
        "DV",
        "Let's Encrypt",
        "15000",
        "KRW",
        "2024-01-01",
        "2025-01-01",
        "true",
        "메인 도메인",
        "본사",
        "",
      ],
      [
        "api.example.com SSL",
        "api.example.com",
        "Route53",
        "WILDCARD",
        "AWS ACM",
        "0",
        "USD",
        "2024-06-01",
        "2025-06-01",
        "true",
        "API 와일드카드 인증서",
        "",
        "",
      ],
    ],
  },
  hardware: {
    label: "하드웨어",
    headers: [
      "name",
      "deviceType",
      "manufacturer",
      "model",
      "serialNumber",
      "assetTag",
      "hostname",
      "os",
      "osVersion",
      "cpu",
      "ram",
      "storage",
      "location",
      "cost",
      "currency",
      "purchaseDate",
      "warrantyEndDate",
      "condition",
      "description",
      "assigneeName",
      "companyName",
      "orgUnitName",
      "ciaC",
      "ciaI",
      "ciaA",
    ],
    sampleRows: [
      [
        "홍길동 MacBook",
        "Laptop",
        "Apple",
        "MacBook Pro 14 M4",
        "C02X1234ABCD",
        "IT-2024-001",
        "hong-mbp",
        "macOS",
        "15.3",
        "Apple M4 Pro",
        "36GB",
        "512GB SSD",
        "본사 3층",
        "3200000",
        "KRW",
        "2024-03-15",
        "2027-03-15",
        "A",
        "개발용 노트북",
        "홍길동",
        "본사",
        "개발팀",
        "2",
        "2",
        "2",
      ],
      [
        "회의실 모니터",
        "Peripheral",
        "Dell",
        "U2723QE",
        "SN-DELL-9876",
        "IT-2024-050",
        "",
        "",
        "",
        "",
        "",
        "",
        "본사 회의실A",
        "650000",
        "KRW",
        "2024-01-10",
        "2027-01-10",
        "A",
        "4K 모니터",
        "",
        "본사",
        "",
        "1",
        "1",
        "1",
      ],
    ],
  },
};

/** Generate a CSV string with BOM prefix for Korean Excel compatibility. */
export function generateTemplateCsv(type: ImportType): string {
  const template = templates[type];
  const BOM = "\uFEFF";
  const headerLine = template.headers.join(",");
  const dataLines = template.sampleRows.map((row) =>
    row.map((cell) => (cell.includes(",") || cell.includes(";") ? `"${cell}"` : cell)).join(",")
  );
  return BOM + [headerLine, ...dataLines].join("\n");
}
